### ISSUE TITLE
Error trapping and timeout?

### ISSUE THREAD

**Issue by jeremymeyers** [urre/albumcoverfinder#3]
Hello! 

Would it be possible to add a way to display when lastfm returns an error? Currently when there are no results it just continues the animated spin gif.

Also might be useful to let people know that the search is exact-only (i.e. no wildcards and it won't return multiple results)

**Comment by urre** [comment]
Hello again @jeremymeyers !

I've pushed a new version v0.7.0 of this plugin. It now has a settings page where you can use your own Last.fm API key. It also adds a simple error message when nothing is found. The spinner will hide when no results are found.

This repo is updated and also https://wordpress.org/plugins/album-cover-finder
